### ISSUE TITLE
orion default config has wrong auth.guard setting

### ISSUE THREAD

**Issue by smarques** [tailflow/laravel-orion-docs#30]
I followed these docs to try Orion (kudos BTW, it seems very nice)
but to make it work with the latest laravel version I had to change a setting in config/orion.pho
I had to set:
'auth' => [
        'guard' => 'sanctum'
    ],

old value was 'api'

I am wondering if I am missing something, but I kept gettting a "Auth guard [api] is not defined" error

HTH

**Comment by alexzarbn** [comment]
Hi @smarques,

Please raise the issue in the main repository of the package, not its docs.
